application: parkcafe-payments
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /payment
  script: payment.application

- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /
  static_dir: www

libraries:
- name: webapp2
  version: "2.5.1"

